# Generated by Django 3.1.4 on 2021-01-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210104_1539'),
        ('articles', '0004_auto_20210105_0859'),
    ]

    operations = [
    ]
